### ISSUE TITLE
Missing buttons

### ISSUE THREAD

**Issue by luckymouse0** [gil-unx/FRONTIER-GATE-BOOST-PLUS#3]
The buttons "Unpack file" and "Repack file" are missing but are present in the tutorial video.

**Comment by gil-unx** [comment]
This happens because the monitor resolution does not match,
im use full hd monitor,
For hd resolution
can use this for a while
https://drive.google.com/file/d/1bQskgElvqmvM5Fp0bLWH0bMm81ClTuSl/view?usp=sharing

**Comment by luckymouse0** [comment]
Thanks that works! Can you tell me where in the source code are these buttons? I don't see them in the forms designer:

![a](https://user-images.githubusercontent.com/15199042/143780860-49c5135c-6af6-47db-952e-fb6c0225cd3e.png)

**Comment by gil-unx** [comment]
> Thanks that works! Can you tell me where in the source code are these buttons? I don't see them in the forms designer:
> 
> ![a](https://user-images.githubusercontent.com/15199042/143780860-49c5135c-6af6-47db-952e-fb6c0225cd3e.png)


Form designer

Line 
130,185
