### ISSUE TITLE
How to contact you?

### ISSUE THREAD

**Issue by Radis3D** [gil-unx/FRONTIER-GATE-BOOST-PLUS#4]
Hello there. I need help with this patching app.
May I know how to contact you?

@gil-unx

**Comment by gil-unx** [comment]
You can contact me at discord Gil_Unx#6732

Pada tanggal Sen, 1 Agt 2022 13.57, Radis 3D ***@***.***>
menulis:

**Comment by Radis3D** [comment]
Already sent, and thanks for the reply.
